### ISSUE TITLE
Every other transaction throws an error

### ISSUE THREAD

**Issue by keorn** [virtualgraham/Neo4jBolt.jl#2] opened 2020-04-11 08:40 UTC
Every other time running a transaction an error is thrown instead of returning:
```
Neo4jBolt.JuliaBolt.CypherSyntaxError("Unexpected end of input: expected whitespace, CYPHER options, EXPLAIN, PROFILE or Query (line 1, column 1 (offset: 0))\n\"\"\n ^", "Neo.ClientError.Statement.SyntaxError", "ClientError", "Statement", "SyntaxError", Dict{Any,Any}("message" => "Unexpected end of input: expected whitespace, CYPHER options, EXPLAIN, PROFILE or Query (line 1, column 1 (offset: 0))\n\"\"\n ^","code" => "Neo.ClientError.Statement.SyntaxError"))
```

**Comment by virtualgraham** [comment] 2020-05-18 04:45
This issue is caused by a feature from Bolt that is no longer supported. https://github.com/neo4j-drivers/neobolt/commit/01f2c2862d8d6985698b9916cce34e7273fcfb38 Fixed in the Bolt repository https://github.com/virtualgraham/JuliaBolt/commit/0ed74375244d44ca33b440d5f5a402e41faaff9f

**Closed as completed by virtualgraham** 2020-05-18 04:45 UTC

**Comment by keorn** [comment] 2020-05-18 07:06
Thanks a lot! Looking forward to try it out.
